# --- !Ups

CREATE TABLE Category (
  "catId" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "name" VARCHAR NOT NULL
);

CREATE TABLE Products (
 "prodId" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
 "title" VARCHAR  NOT NULL,
 "description" TEXT NOT NULL,
 "quantity" INTEGER NOT NULL,
 "price" FLOAT NOT NULL,
 "catId" int not null,
 foreign key("catId") references Category(catId) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE Payment (
  "paymentId" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "name" VARCHAR NOT NULL
);


CREATE TABLE Shipping (
  "shippingId" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "name" VARCHAR NOT NULL,
  "price" INT NOT NULL
);


CREATE TABLE Cart (
 prodId INTEGER PRIMARY KEY NOT NULL,
 FOREIGN KEY(prodId) REFERENCES Products(prodId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Opinion (
 "opinionId" INTEGER PRIMARY KEY NOT NULL,
 "prodId" INTEGER NOT NULL,
 "content" VARCHAR NOT NULL,
 FOREIGN KEY(prodId) REFERENCES Products(prodId) ON DELETE CASCADE ON UPDATE CASCADE
);

# --- !Downs

DROP TABLE Products;
drop table Category;
DROP TABLE Payment;
DROP TABLE Shipping;
DROP TABLE Cart;
DROP TABLE Opinion;